import Head from "next/head";
import Image from "next/image";
import Card from "../components/Card";
import styles from "../styles/Home.module.css";
import React,{useEffect, useState} from "react";

export default function Home() {

  const [imgs, setImgs] = useState(null);

  const fetchImg = async () => {
    const response = await fetch(`https://picsum.photos/v2/list?page=2&limit=8`);
    let data = await response.json();
    data=data.concat(data);
    let randData = data.sort(() => Math.random() -0.5);

    console.log(randData);
    setImgs(randData);
  };

  useEffect(() => {
    fetchImg();

  },[]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <h1>Card Match Game</h1>
      <div className={styles.cardSize}>
       {imgs?.map((img,i)=> <Card img={img} key={i}/>) }
      </div>
     
        
      </main>
    </div>
  );
}
